#!/bin/bash
set -e

BACKUP_DIR=${TOPDIR}/configure/backup
BIN=/usr/bin
CONF_DIR=${TOPDIR}/configure/${TARGET}
CONFIGS=""

confirm() {
    # call with a prompt string or use a default
    read -r -p "${1:-Are you sure? [y/N]} " response
    case "$response" in
        [yY][eE][sS]|[yY])
			msg "yes"
            true
        ;;
        *)
			msg "no"
            false
     ;;
    esac
}

msg() {
	echo $1
}
