#!/bin/bash
set -e

# directories
TOP_DIR="$( cd "$( dirname "$BASH_SOURCE" )" && pwd -P )"
WS_DIR=`pwd -P`

usage() {
	echo "Usage: $(basename $0) [--help] [--target=<env>]"
	echo ""
	echo "	===== options ====="
	echo "	--help: print usage"
	echo "	--target=<env>: select setting env"
	echo "	==================="
	echo ""
	echo "	e.g. setting \"vi\" env"
	echo ""
	echo "	$ cd workspace"
	echo "	$ ./set --target=vi"
	exit 0
}

# option parsing
for opt in $@; do
	case ${opt} in
		--help)
		usage
		;;
		--target=*)
		TARGET=${opt#*=}
		;;
		*)
		echo "Invalid option"
		;;
	esac
done

# includes
. ${TOP_DIR}/time
. ${TOP_DIR}/prefix
. ${TOP_DIR}/common-functions

SPEED=${FAST}

basic_set() {
	fix_env
	install_packages
	config_bak
	config_all
	apply_all
}

custom_set() {
	fix_env
	# custum
	# ...

}

basic_set
#custom_set
