#!/bin/bash
set -e

# functions
. ${TOP_DIR}/common

# default config function
_set_config() {
	add_repository
	install_packages

	if [ -n "$(ls ${TOP_DIR} | grep backup)" ]; then
		echo "===== WARNING! There are backup files already. ====="
		confirm "Do you still want to proceed with the backup? (Y/n)?" \
			&& workspace_backup
	else
		workspace_backup
	fi
	workspace_config
}
